### ISSUE TITLE
Adjustments to UI and readability

### ISSUE THREAD

**Issue by taniarascia** [halfer/php-tutorial-text#22]
Here are a few CSS adjustments for improved readability for your consideration.

#### Current:

```css
#content .sidebar {
    border: 1px dashed silver;
    margin: 0 4em;
    padding: 0 8px;
}

```

#### New:

```css
#content .sidebar {
    border: 1px dashed #247EDA;
    background: #e9f2fb;
    margin: 2em 0;
    padding: 1.5em;
}

#content .sidebar p {
    margin: 1.5em 0;
}
```

#### Current:

```css
#content p, #content ul, #content ol {
    font-size: 1.3em;
}

#content p {
    margin: 16px 0;
    line-height: 140%;
}
```

```css
#content code {
    font-size: 1.1em;
}
```

#### New:

```css
#content p, #content ul, #content ol {
    font-size: 1.1em;
    line-height: 1.6;
    font-weight: 400;
    margin: 1.5em 0;
}
```

```css
#content code {
    font-size: 1.1em;
    background: rgba(0, 0, 0, .08);
}

#content pre code {
    background: transparent
}
```

I would also probably make the alert note stand out more.

#### Current:

```css
#versions-note {
    min-width: 850px;
    max-width: 1000px;
    margin: 0 auto;
    font-family: "Open Sans",sans-serif;
    font-weight: 300;
    border: 1px dotted gray;
    color: gray;
}
````

#### New:

```css
#versions-note {
    border: 1px dotted #EEA09F;
    color: #B02323;
    background: #fbeceb;
    line-height: 1.6;
    font-weight: bold;
}

#versions-note #versions-note-inner {
    padding: 1.5em;
    font-size: 1em;
}
```

```css
#content {
   color: #333333;
}
```

[Here's an example image](http://imgur.com/a/3V3KU).

I would also consider removing `margin-top: 0` from `h1` and `#contents-menu h2`, as well as making headings bold.
